version: '3.8'
services:
  wallet-client:
    build:
      context: .
      dockerfile: Dockerfile-client
      args:
        REACT_APP_CLIENT_DOMAIN: wallet.zingypay.com
        REACT_APP_WALLET_BACKEND_ENDPOINT: https://wallet.zingypay.com
      - .env
    ports:
      - "8000:80"
