version: '3.8'
services:
  wallet-client:
    build:
      context: .
      dockerfile: Dockerfile-client
      args:
        REACT_APP_CLIENT_DOMAIN: docker.for.mac.host.internal:7000
        REACT_APP_WALLET_BACKEND_ENDPOINT: http://localhost
    env_file:
      - .env
    ports:
      - "8000:80"
