version: '3.8'
services:
  wallet-client:
    build:
      context: .
      dockerfile: Dockerfile-client
      args:
        REACT_APP_CLIENT_DOMAIN: paygod.godstabernacle.xyz
        REACT_APP_WALLET_BACKEND_ENDPOINT: https://paygod.godstabernacle.xyz
    env_file:
      - .env
    ports:
      - "8000:80"
