VERSION = "2.5.0"
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"
TRANSFER_SERVER = "https://paygod.godstabernacle.xyz/sep24"
TRANSFER_SERVER_SEP0024 = "https://paygod.godstabernacle.xyz/sep24"
KYC_SERVER = "https://paygod.godstabernacle.xyz/kyc"
WEB_AUTH_ENDPOINT = "https://paygod.godstabernacle.xyz/auth"
SIGNING_KEY = "GBU2XFD6OKDWH4IJXJVJTLU74HQQIUOPTYWERWOJ4D56KQSH2FDBGKGL"
ACCOUNTS = [ "GAWTB6UKQ6DJSMAPTNLB2TJVCKWPCT4NHLAFPC5EGOZVXK6XF47UGSMG", "GBXGB4HLOX6B7G7XAPCDRRTFZCWA6JOO4YT42JXWQJHNP2MLIURCKMPJ", "GAIXTJGANTERAERDZN72GJTAU4YYEFH2HZNKDDBWQKFY7W6LC4WLLVHV", "GAIXTJGANTERAERDZN72GJTAU4YYEFH2HZNKDDBWQKFY7W6LC4WLLVHV", "GAIXTJGANTERAERDZN72GJTAU4YYEFH2HZNKDDBWQKFY7W6LC4WLLVHV", "GAIXTJGANTERAERDZN72GJTAU4YYEFH2HZNKDDBWQKFY7W6LC4WLLVHV", "GAIXTJGANTERAERDZN72GJTAU4YYEFH2HZNKDDBWQKFY7W6LC4WLLVHV", "GAIXTJGANTERAERDZN72GJTAU4YYEFH2HZNKDDBWQKFY7W6LC4WLLVHV", "GAIXTJGANTERAERDZN72GJTAU4YYEFH2HZNKDDBWQKFY7W6LC4WLLVHV", "GAIXTJGANTERAERDZN72GJTAU4YYEFH2HZNKDDBWQKFY7W6LC4WLLVHV", "GAIXTJGANTERAERDZN72GJTAU4YYEFH2HZNKDDBWQKFY7W6LC4WLLVHV", "GAIXTJGANTERAERDZN72GJTAU4YYEFH2HZNKDDBWQKFY7W6LC4WLLVHV",]
DIRECT_PAYMENT_SERVER = "https://paygod.godstabernacle.xyz/sep31"
ANCHOR_QUOTE_SERVER = "https://paygod.godstabernacle.xyz/sep38"

[[CURRENCIES]]
code = "USDN"
issuer = "GBSBVFTPVRTCIM3DCDOXNRTAPPTJQBRLPNVQYKFUTHLMDR43HJYO2YHZ"
status = "test"
name = "NATURE DOLLAR"
is_asset_anchored = true
anchor_asset_type = "crypto"
anchor_asset = "NATUREUSD"
home_domain = "paygod.godstabernacle.xyz"
redemption_instructions = "Get your asset via our wallets"

[[CURRENCIES]]
code = "NATUREUSD"
issuer = "GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK"
status = "test"
is_asset_anchored = true
anchor_asset_type = "fiat"
home_domain = "paygod.godstabernacle.xyz"
desc = "A test NATUREUSD issued by Global Fund 4 Nature."

[[CURRENCIES]]
code = "NATURENGN"
issuer = "GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK"
status = "test"
is_asset_anchored = true
anchor_asset_type = "fiat"
home_domain = "paygod.godstabernacle.xyz"
desc = "A test NATURENGN issued by Global Fund 4 Nature."

[[CURRENCIES]]
code = "NATUREURO"
issuer = "GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK"
status = "test"
is_asset_anchored = true
anchor_asset_type = "fiat"
home_domain = "paygod.godstabernacle.xyz"
desc = "A test NATUREURO issued by Global Fund 4 Nature."

[[CURRENCIES]]
code = "NATURECFA"
issuer = "GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK"
status = "test"
is_asset_anchored = true
anchor_asset_type = "fiat"
home_domain = "paygod.godstabernacle.xyz"
desc = "A test NATURECFA issued by Global Fund 4 Nature."

[[CURRENCIES]]
code = "NATUREGBP"
issuer = "GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK"
status = "test"
is_asset_anchored = true
anchor_asset_type = "fiat"
home_domain = "paygod.godstabernacle.xyz"
desc = "A test NATUREGBP issued by Global Fund 4 Nature."

[[CURRENCIES]]
code = "NATUREJPY"
issuer = "GA3BJUBNOIHANBJEKZFSQTCRB5CUQ4GSENQHVC5QNZGGSK3ILAZS6ATK"
status = "test"
is_asset_anchored = true
anchor_asset_type = "fiat"
home_domain = "paygod.godstabernacle.xyz"
desc = "A test NATUREJPY issued by Global Fund 4 Nature."

[DOCUMENTATION]
ORG_NAME = "Global Fund 4 Nature"
ORG_URL = "https://www.gf4n.xyz"
ORG_LOGO = "https://www.gf4n.xyz/logo"
ORG_DESCRIPTION = "Recreo; Replete Terram"
ORG_TWITTER = "nature2471"
ORG_GITHUB = "nature-smartchain"
ORG_OFFICIAL_EMAIL = "info@gf4n.xyz"
ORG_SUPPORT_EMAIL = "support@gf4n.xyz"
